#ansible-playbook -vvv -i inventory/hosts.yaml playbook/generate_config.yaml
---
- name: Apply VRF Configuration 
  hosts: an1
  connection: juniper.device.pyez
  gather_facts: true
  tags: juniper


  vars:
    config_dir: "tmp"
    config_filename: "{{ config_dir }}/{{ inventory_hostname }}.conf"

  tasks:
    - name: Confirm/Create device configuration directory
      file:
          path: "{{ config_dir }}"
          state: directory
      run_once: yes
      delegate_to: localhost

    - name: Build Configuration
      template: src="vrf.j2" dest={{ config_filename }}

    - name: Apply Configuration
      junos_config:
        src: "{{ config_filename }}"
      register: response