#ansible-playbook -i inventory/kpn.yaml playbook/bgp.yaml
---
- name: Configure BGP
  hosts: all:!qfx:!core
  connection: juniper.device.pyez
  gather_facts: false
  tags: juniper


  vars:
    config_dir: "tmp"
    config_filename: "{{ config_dir }}/{{ inventory_hostname }}.conf"

  tasks:
    - name: Confirm/Create device configuration directory
      file:
          path: "{{ config_dir }}"
          state: directory
      run_once: yes
#      delegate_to: localhost

    - name: Build Configuration
      template: src="bgp.j2" dest={{ config_filename }}

    - name: Apply Configuration
      junos_config:
        src: "{{ config_filename }}"
      register: response
