# ansible-playbook -i inventory/kpn.yaml playbook/l3vpn-mx.yaml
---
- name: Apply L3VPN Configuration 
  hosts: svc
  connection: juniper.device.pyez
  gather_facts: false
  tags: juniper

  vars:
    config_dir: "configs/kpn/services/l3vpn"
    config_filename: "{{ config_dir }}/{{ inventory_hostname }}.cfg"

  tasks:
    - name: Generate Config
      command: "python3 {{ playbook_dir }}/library/l3vpn-mx.py {{ lo0 }} {{ l3vpn.iface }} {{ l3vpn.esi_base }} {{ l3vpn.ip_base_v4 }} \
          {{ l3vpn.ip_base_v6 }} {{ l3vpn.step }} {{ l3vpn.site_id }} {{ l3vpn_aa.vlan_start }} {{ l3vpn.vlan_end }}"
      register: config
 
    - name: copy the output to a local file
      copy:
        content: "{{ config.stdout }}"
        dest: "{{ config_filename }}"  

    - name: Apply Configuration
      junos_config:
        update: replace
        src: "{{ config_filename }}"
        src_format: set
      register: response
